<!DOCTYPE html>

<head>

    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Сайт кинологического питомника Кастор*С Хаус. Разведение Австралийских хилеров, КА ДЕ БО и минибулей. Хозяйка питомника - Попова Ольга"/>
    <meta name="keywords" content="heeler, kadebou, minibull, хилер, кадебо, минибуль, миниатюрный бультерьер, питомник, щенки"/>
    <meta name="author" content="grigory.panov at gmail.com"/>
    <link rel="icon" href="/icons/favicon.ico"/>

    <title>Кастор*С Хаус. Кинологический питомник</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet"/>

    <!-- Custom styles for this template -->
    <link href="/css/castorshouse.css" rel="stylesheet"/>

    <!-- image gallery -->
    <link rel="stylesheet" href="/css/blueimp-gallery.min.css"/>

    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67826869-1', 'auto');
  ga('send', 'pageview');


    </script>
</head>
