<!DOCTYPE html>

<head>

    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <link rel="icon" href="/icons/favicon.ico"/>

    <title>Кастор*С Хаус. Админ.</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet"/>

    <!-- Custom styles for this template -->
    <link href="/css/castorshouse.css" rel="stylesheet"/>

    <!-- markdown redactor -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'/>
    <link rel="stylesheet" href="/css/markdowneditor.css"/>

</head>